export const TYPES = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED:'LOGIN_FAILED',
  LOG_OUT:'LOG_OUT',
  EXPIRED_TOKEN:'EXPIRED_TOKEN',
  GET_PROVINCE_SUCCESS:'GET_PROVINCE_SUCCESS',
  GET_PROVINCE_FAILED:'GET_PROVINCE_FAILED',
  GET_CONSTRUCTION_STATUS_SUCCESS:'GET_CONSTRUCTION_STATUS_SUCCESS',
  GET_CONSTRUCTION_STATUS_FAILED:' GET_CONSTRUCTION_STATUS_FAILED',
  GET_CONSTRUCTIONS_SUCCESS:'GET_CONSTRUCTION_STATUS_SUCCESS',
  GET_CONSTRUCTIONS_FAILED:' GET_CONSTRUCTION_STATUS_FAILED',
  GET_CONSTRUCTIONS_DETAIL_SUCCESS:'GET_CONSTRUCTION_STATUS_SUCCESS',
  GET_CONSTRUCTIONS_DETAIL_FAILED:' GET_CONSTRUCTION_STATUS_FAILED',
  GET_LIST_CONSTRUCTION_SUCCESS:'GET_CONSTRUCTION_STATUS_SUCCESS',
  GET_lIST_CONSTRUCTION_FAILED:' GET_CONSTRUCTION_STATUS_FAILED',

  SET_LANGUAGE: 'SET_LANGUAGE'

};
  